"""create circular notices table

Revision ID: 146eb918cdd4
Revises: 66610768821e
Create Date: 2026-09-04 11:51:02.023826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '146eb918cdd4'
down_revision: Union[str, Sequence[str], None] = '66610768821e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circular_notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum('CIRCULAR', 'NOTICE', name='circular_notice_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('notice_date', sa.Date(), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circular_notices_content_type'), 'circular_notices', ['content_type'], unique=False)
    op.create_index(op.f('ix_circular_notices_id'), 'circular_notices', ['id'], unique=False)
    op.create_index(op.f('ix_circular_notices_is_featured'), 'circular_notices', ['is_featured'], unique=False)
    op.create_index(op.f('ix_circular_notices_is_published'), 'circular_notices', ['is_published'], unique=False)
    op.create_index(op.f('ix_circular_notices_notice_date'), 'circular_notices', ['notice_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_circular_notices_notice_date'), table_name='circular_notices')
    op.drop_index(op.f('ix_circular_notices_is_published'), table_name='circular_notices')
    op.drop_index(op.f('ix_circular_notices_is_featured'), table_name='circular_notices')
    op.drop_index(op.f('ix_circular_notices_id'), table_name='circular_notices')
    op.drop_index(op.f('ix_circular_notices_content_type'), table_name='circular_notices')
    op.drop_table('circular_notices')
    # ### end Alembic commands ###
