"""create downloads table

Revision ID: 1ee2ca611bf8
Revises: 93bc1e2017b3
Create Date: 2026-09-25 15:34:03.946375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ee2ca611bf8'
down_revision: Union[str, Sequence[str], None] = '93bc1e2017b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon_type', sa.String(length=20), server_default='lucide', nullable=False),
    sa.Column('icon_key', sa.String(length=80), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('original_file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_downloads_created_by_id'), 'downloads', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_downloads_display_order'), 'downloads', ['display_order'], unique=False)
    op.create_index(op.f('ix_downloads_icon_type'), 'downloads', ['icon_type'], unique=False)
    op.create_index(op.f('ix_downloads_id'), 'downloads', ['id'], unique=False)
    op.create_index(op.f('ix_downloads_is_active'), 'downloads', ['is_active'], unique=False)
    op.create_index(op.f('ix_downloads_title'), 'downloads', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_downloads_title'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_is_active'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_id'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_icon_type'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_display_order'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_created_by_id'), table_name='downloads')
    op.drop_table('downloads')
    # ### end Alembic commands ###
