"""create news items table

Revision ID: 5f3a0b391ae7
Revises: 0b5a096954a3
Create Date: 2026-09-02 11:14:52.839837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f3a0b391ae7'
down_revision: Union[str, Sequence[str], None] = '0b5a096954a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_type', sa.Enum('NEWS', 'ANNOUNCEMENT', name='news_content_type', native_enum=False), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_items_content_type'), 'news_items', ['content_type'], unique=False)
    op.create_index(op.f('ix_news_items_created_by_id'), 'news_items', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_news_items_is_published'), 'news_items', ['is_published'], unique=False)
    op.create_index(op.f('ix_news_items_published_at'), 'news_items', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_items_slug'), 'news_items', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_items_slug'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_published_at'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_is_published'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_created_by_id'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_content_type'), table_name='news_items')
    op.drop_table('news_items')
    # ### end Alembic commands ###
