"""create faculty categories and members

Revision ID: 93bc1e2017b3
Revises: e63235b845c2
Create Date: 2026-09-22 12:32:59.631251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93bc1e2017b3'
down_revision: Union[str, Sequence[str], None] = 'e63235b845c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_faculty_categories_name'),
    sa.UniqueConstraint('slug', name='uq_faculty_categories_slug')
    )
    op.create_index(op.f('ix_faculty_categories_display_order'), 'faculty_categories', ['display_order'], unique=False)
    op.create_index(op.f('ix_faculty_categories_id'), 'faculty_categories', ['id'], unique=False)
    op.create_index(op.f('ix_faculty_categories_is_active'), 'faculty_categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_faculty_categories_name'), 'faculty_categories', ['name'], unique=False)
    op.create_index(op.f('ix_faculty_categories_slug'), 'faculty_categories', ['slug'], unique=False)
    op.create_table('faculty_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('designation', sa.String(length=180), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=False),
    sa.Column('experience_years', sa.Integer(), server_default='0', nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['faculty_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculty_members_category_id'), 'faculty_members', ['category_id'], unique=False)
    op.create_index(op.f('ix_faculty_members_created_by_id'), 'faculty_members', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_faculty_members_display_order'), 'faculty_members', ['display_order'], unique=False)
    op.create_index(op.f('ix_faculty_members_id'), 'faculty_members', ['id'], unique=False)
    op.create_index(op.f('ix_faculty_members_is_active'), 'faculty_members', ['is_active'], unique=False)
    op.create_index(op.f('ix_faculty_members_name'), 'faculty_members', ['name'], unique=False)
    op.create_index(op.f('ix_faculty_members_subject'), 'faculty_members', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faculty_members_subject'), table_name='faculty_members')
    op.drop_index(op.f('ix_faculty_members_name'), table_name='faculty_members')
    op.drop_index(op.f('ix_faculty_members_is_active'), table_name='faculty_members')
    op.drop_index(op.f('ix_faculty_members_id'), table_name='faculty_members')
    op.drop_index(op.f('ix_faculty_members_display_order'), table_name='faculty_members')
    op.drop_index(op.f('ix_faculty_members_created_by_id'), table_name='faculty_members')
    op.drop_index(op.f('ix_faculty_members_category_id'), table_name='faculty_members')
    op.drop_table('faculty_members')
    op.drop_index(op.f('ix_faculty_categories_slug'), table_name='faculty_categories')
    op.drop_index(op.f('ix_faculty_categories_name'), table_name='faculty_categories')
    op.drop_index(op.f('ix_faculty_categories_is_active'), table_name='faculty_categories')
    op.drop_index(op.f('ix_faculty_categories_id'), table_name='faculty_categories')
    op.drop_index(op.f('ix_faculty_categories_display_order'), table_name='faculty_categories')
    op.drop_table('faculty_categories')
    # ### end Alembic commands ###
