"""create gallery albums and images tables

Revision ID: e63235b845c2
Revises: 146eb918cdd4
Create Date: 2026-09-09 11:34:20.654253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e63235b845c2'
down_revision: Union[str, Sequence[str], None] = '146eb918cdd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_albums_category'), 'gallery_albums', ['category'], unique=False)
    op.create_index(op.f('ix_gallery_albums_created_by_id'), 'gallery_albums', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_gallery_albums_id'), 'gallery_albums', ['id'], unique=False)
    op.create_index(op.f('ix_gallery_albums_is_published'), 'gallery_albums', ['is_published'], unique=False)
    op.create_index(op.f('ix_gallery_albums_year'), 'gallery_albums', ['year'], unique=False)
    op.create_table('gallery_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_homepage', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('homepage_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['gallery_albums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_images_album_id'), 'gallery_images', ['album_id'], unique=False)
    op.create_index(op.f('ix_gallery_images_homepage_order'), 'gallery_images', ['homepage_order'], unique=False)
    op.create_index(op.f('ix_gallery_images_id'), 'gallery_images', ['id'], unique=False)
    op.create_index(op.f('ix_gallery_images_is_homepage'), 'gallery_images', ['is_homepage'], unique=False)
    op.create_index(op.f('ix_gallery_images_sort_order'), 'gallery_images', ['sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gallery_images_sort_order'), table_name='gallery_images')
    op.drop_index(op.f('ix_gallery_images_is_homepage'), table_name='gallery_images')
    op.drop_index(op.f('ix_gallery_images_id'), table_name='gallery_images')
    op.drop_index(op.f('ix_gallery_images_homepage_order'), table_name='gallery_images')
    op.drop_index(op.f('ix_gallery_images_album_id'), table_name='gallery_images')
    op.drop_table('gallery_images')
    op.drop_index(op.f('ix_gallery_albums_year'), table_name='gallery_albums')
    op.drop_index(op.f('ix_gallery_albums_is_published'), table_name='gallery_albums')
    op.drop_index(op.f('ix_gallery_albums_id'), table_name='gallery_albums')
    op.drop_index(op.f('ix_gallery_albums_created_by_id'), table_name='gallery_albums')
    op.drop_index(op.f('ix_gallery_albums_category'), table_name='gallery_albums')
    op.drop_table('gallery_albums')
    # ### end Alembic commands ###
